export const comments = [
    {
        id: '1',
        user_id: '328193ybdhad',
        commentable_type: 'POST',
        commentable_id: 1,
        content: 'Hello anh em',
        created_at: '10 ngay truoc',
        created_at: '10 ngay truoc',
    },
    {
        id: '2',
        user_id: '328193ybdhad',
        commentable_type: 'POST',
        commentable_id: 1,
        content: 'Chao ban',
        created_at: '10 ngay truoc',
        created_at: '10 ngay truoc',
    },
    {
        id: '3',
        user_id: '328193ybdhad',
        commentable_type: 'POST',
        commentable_id: 1,
        content: 'Hello',
        created_at: '10 ngay truoc',
        created_at: '10 ngay truoc',
    },
    {
        id: '4',
        user_id: '328193ybdhad',
        commentable_type: 'COMMENT',
        commentable_id: 1,
        content: 'TOI DAY',
        created_at: '10 ngay truoc',
        created_at: '10 ngay truoc',
    },
    {
        id: '5',
        user_id: '328193ybdhad',
        commentable_type: 'COMMENT',
        commentable_id: 4,
        content: 'UM',
        created_at: '10 ngay truoc',
        created_at: '10 ngay truoc',
    },
    {
        id: '6',
        user_id: '328193ybdhad',
        commentable_type: 'COMMENT',
        commentable_id: 4,
        content: 'UM',
        created_at: '10 ngay truoc',
        created_at: '10 ngay truoc',
    },
    {
        id: '7',
        user_id: '328193ybdhad',
        commentable_type: 'COMMENT',
        commentable_id: 6,
        content: 'CHHAHA',
        created_at: '10 ngay truoc',
        created_at: '10 ngay truoc',
    },
];
